name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Enable IPv6 connectivity using Cloudflare WARP
      - name: Set up WARP for IPv6
        uses: fscarmen/warp-on-actions@v1.1
        with:
          stack: dual
      
      - name: Test IPv6 connectivity
        run: |
          echo "Testing IPv6 connectivity..."
          curl -m 9 --ipv6 --verbose https://google.com || echo "IPv6 test failed but continuing..."
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Generate Prisma client
        run: npx prisma generate
      
      - name: Build app
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
      
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          timeout: 60s
          command_timeout: 30s
          debug: true
          script: |
            echo "Connected successfully!"
            pwd
            whoami
      
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          protocol: tcp6
          port: 22
          timeout: 60s
          command_timeout: 120s
          script: |
            set -e
            echo "Checking if app directory exists..."
            if [ ! -d "${{ secrets.APP_DIR }}/.git" ]; then
              echo "Directory does not exist or is not a git repo. Creating and cloning repository..."
              mkdir -p ${{ secrets.APP_DIR }}
              cd ${{ secrets.APP_DIR }}
              git clone https://github.com/${{ github.repository }}.git .
            fi
            
            echo "Navigating to app directory..."
            cd ${{ secrets.APP_DIR }}
            
            echo "Pulling latest changes..."
            git pull origin main
            
            echo "Installing dependencies..."
            npm install --omit=dev
            
            echo "Generating Prisma client..."
            npx prisma generate
            
            echo "Building application..."
            npm run build
            
            echo "Running database migrations..."
            npx prisma migrate deploy
            
            echo "Managing PM2 process..."
            if pm2 list | grep -q "chat-api"; then
              echo "Restarting existing PM2 process..."
              pm2 restart chat-api
            else
              echo "Starting new PM2 process..."
              pm2 start dist/server.js --name chat-api
            fi
            
            echo "Saving PM2 configuration..."
            pm2 save
            
            echo "Deployment completed successfully!"