version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.8
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to VPS
          command: |
            ssh -tt -o StrictHostKeyChecking=no deployer@${SERVER_IP} \<< 'EOF'
            set -x   # This will print each command as it runs
            cd ~/chat-api || git clone https://github.com/oscarbrehier/chat-api.git ~/chat-api
            cd ~/chat-api
            git pull origin main
            npm install
            export DATABASE_URL="${DATABASE_URL}"
            npx prisma generate
            npm run build
            pm2 restart chat-api || pm2 start dist/src/server.js --name chat-api
            EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
