version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:20
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
  docker:
    - image: circleci/node:20
  working_directory: ~/repo
  steps:
    - attach_workspace:
        at: ~/repo
    - run:
        name: Deploy to VPS
        command: |
          ssh -o StrictHostKeyChecking=no deployer@${SERVER_IP} \<< 'EOF'
          cd ~/chat-api || git clone https://github.com/oscarbrehier/chat-api.git ~/chat-api
          cd ~/chat-api
          git pull origin main
          npm install

          # Generate Prisma client
          npx prisma generate

          # Build project
          npm run build

          # Restart app with PM2
          pm2 restart chat-api || pm2 start dist/src/server.js --name chat-api
          EOF

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
